language: php

services:
  - docker

before_install:
  - composer self-update
  - composer create-project --prefer-dist laravel/laravel laraship
  - cd laraship
  - cp .env.example .env
  - php artisan key:generate

script:
  - docker-compose up -d
  - docker ps
  - docker ps -a --filter "status=running" -q -s | wc -l | xargs -I % test % -eq 4
